name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - numpy
  - pandas
  - matplotlib
  - scipy
  - obspy
  - dash
  - dash-bootstrap-components
  - dash-core-components
  - dash-html-components
  - dash-iconify
  - dash-mantine-components
  - dash-table
  - dash-tools